schedule:
  every_minutes: 5
  parallel: false
clusters:
  - name: icDial-Cluster-A
    enabled: false
    type: sftp
    host: "10.10.1.15"
    port: 22
    username: "loguser"
    key_path: "/secrets/id_rsa"
    log_path: "/var/log/vicidial"
    log_types:
      - name: apache
        path: /cluster1/apache_logs
      - name: mysql
        path: /cluster1/mysql_logs

  - name: Local-Error-Logs
    enabled: true
    type: local
    log_path: "/host_logs"
    log_types:
      - name: apache
        path: /host_logs
        pattern: "error_*.log"   # Only pick files that start with error_
        include_regex: "(ERROR|CRITICAL|FATAL|Exception|Traceback)"
        exclude_regex: "(INFO|DEBUG)"
        parser: apache_regex
      - name: mysql
        path: /host_logs
        pattern: "error_*.log"   # Only pick files that start with error_
      - name: laravel
        path: /host_logs
        pattern: "error_*.log"   # Only pick files that start with error_
        parser: mysql_regex


  - name: icDial-Cluster-B
    enabled: false
    type: local
    log_path: "./sample_logs"
    log_types:
      - name: apache
        path: /cluster1/apache_logs
      - name: mysql
        path: /cluster1/mysql_logs
      - name: asterisk
        path: "/var/log/asterisk"
        file_glob: "full-*.log"
        include_regex: "(ERROR|FAIL|Exception)"
        parser: asterisk_regex

